export const PANEL_EVENT_TYPE_LABEL: Record<string, string> = {
  'inbox:new_chat': 'Novo chat',
  'inbox:new_message': 'Mensagem',
  'inbox:priority': 'Prioridade',
  'inbox:priority_expired': 'Pode puxar',
  'inbox:supervisor_help': 'Ajuda supervisor',
  'inbox:queue_sla': 'Fila parada',
  'inbox:ticket_sla': 'SLA ticket',
  'webchat:escalated': 'Chat do site',
  'webchat:fallback_missed': 'Fallback WA',
  'whatsapp:disconnected': 'WhatsApp',
  'whatsapp:connected': 'WhatsApp',
  'billing:plan_expiring': 'Plano',
  'billing:plan_expired': 'Plano',
  'billing:messages_quota_exceeded': 'Cota mensagens',
  'ai:quota_exceeded': 'IA esgotada',
  'ai:quota_low': 'IA baixa',
  'system:critical_config': 'Config crítica',
}
